// ignore_for_file: constant_identifier_names
enum WeatherLanguage {
  Afrikaans('af'),
  Albanian('al'),
  Arabic('ar'),
  Azerbaijani('az'),
  Bulgarian('bg'),
  Catalan('ca'),
  Czech('cz'),
  Danish('da'),
  German('de'),
  Greek('el'),
  English('en'),
  Basque('eu'),
  Persian('fa'),
  Farsi('fa'),
  Finnish('fi'),
  French('fr'),
  Galician('gl'),
  Hebrew('he'),
  Hindi('hi'),
  Croatian('hr'),
  Hungarian('hu'),
  Indonesian('id'),
  Italian('it'),
  Japanese('ja'),
  Korean('kr'),
  Latvian('la'),
  Lithuanian('lt'),
  Macedonian('mk'),
  Norwegian('no'),
  Dutch('nl'),
  Polish('pl'),
  Portuguese('pt'),
  PortugueseBrazilian('pt_br'),
  Romanian('ro'),
  Russian('ru'),
  Swedish('sv'),
  Slovak('sk'),
  Slovenian('sl'),
  Spanish('sp'),
  Serbian('sr'),
  Thai('th'),
  Turkish('tr'),
  Ukrainian('ua'),
  Vietnamese('vi'),
  ChineseSimplified('zh_cn'),
  ChineseTraditional('zh_tw'),
  Zulu('zu');

  const WeatherLanguage(this.code);

  final String code;
}

// todo - create const map?
final Map<String, WeatherLanguage> languageCodeReverse = {
  for (WeatherLanguage wl in WeatherLanguage.values) wl.code: wl
};

//
// /// Расширение, чтобы правильно отразить название языка.
// extension ParseToString on WeatherLanguage {
//   String toShortString() {
//     final String short = toString().split('.').last;
//     return short.substring(0, 1).toUpperCase() + short.substring(1);
//   }
// }
//
// final languageCode = <WeatherLanguage, String>{
//   WeatherLanguage.afrikaans: 'af',
//   WeatherLanguage.albanian: 'al',
//   WeatherLanguage.arabic: 'ar',
//   WeatherLanguage.azerbaijani: 'az',
//   WeatherLanguage.bulgarian: 'bg',
//   WeatherLanguage.catalan: 'ca',
//   WeatherLanguage.czech: 'cz',
//   WeatherLanguage.danish: 'da',
//   WeatherLanguage.german: 'de',
//   WeatherLanguage.greek: 'el',
//   WeatherLanguage.english: 'en',
//   WeatherLanguage.basque: 'eu',
//   WeatherLanguage.persian: 'fa',
//   WeatherLanguage.farsi: 'fa',
//   WeatherLanguage.finnish: 'fi',
//   WeatherLanguage.french: 'fr',
//   WeatherLanguage.galician: 'gl',
//   WeatherLanguage.hebrew: 'he',
//   WeatherLanguage.hindi: 'hi',
//   WeatherLanguage.croatian: 'hr',
//   WeatherLanguage.hungarian: 'hu',
//   WeatherLanguage.indonesian: 'id',
//   WeatherLanguage.italian: 'it',
//   WeatherLanguage.japanese: 'ja',
//   WeatherLanguage.korean: 'kr',
//   WeatherLanguage.latvian: 'la',
//   WeatherLanguage.lithuanian: 'lt',
//   WeatherLanguage.macedonian: 'mk',
//   WeatherLanguage.norwegian: 'no',
//   WeatherLanguage.dutch: 'nl',
//   WeatherLanguage.polish: 'pl',
//   WeatherLanguage.portuguese: 'pt',
//   WeatherLanguage.portugueseBrazilian: 'pt_br',
//   WeatherLanguage.romanian: 'ro',
//   WeatherLanguage.russian: 'ru',
//   WeatherLanguage.swedish: 'sv',
//   WeatherLanguage.slovak: 'sk',
//   WeatherLanguage.slovenian: 'sl',
//   WeatherLanguage.spanish: 'sp',
//   WeatherLanguage.serbian: 'sr',
//   WeatherLanguage.thai: 'th',
//   WeatherLanguage.turkish: 'tr',
//   WeatherLanguage.ukrainian: 'ua',
//   WeatherLanguage.vietnamese: 'vi',
//   WeatherLanguage.chineseSimplified: 'zh_cn',
//   WeatherLanguage.chineseTraditional: 'zh_tw',
//   WeatherLanguage.zulu: 'zu',
// };
//
// final languageCodeReverse = <String, WeatherLanguage>{
//   'af': WeatherLanguage.afrikaans,
//   'al': WeatherLanguage.albanian,
//   'ar': WeatherLanguage.arabic,
//   'az': WeatherLanguage.azerbaijani,
//   'bg': WeatherLanguage.bulgarian,
//   'ca': WeatherLanguage.catalan,
//   'cz': WeatherLanguage.czech,
//   'da': WeatherLanguage.danish,
//   'de': WeatherLanguage.german,
//   'el': WeatherLanguage.greek,
//   'en': WeatherLanguage.english,
//   'eu': WeatherLanguage.basque,
//   'fa': WeatherLanguage.farsi, // persian too
//   'fi': WeatherLanguage.finnish,
//   'fr': WeatherLanguage.french,
//   'gl': WeatherLanguage.galician,
//   'he': WeatherLanguage.hebrew,
//   'hi': WeatherLanguage.hindi,
//   'hr': WeatherLanguage.croatian,
//   'hu': WeatherLanguage.hungarian,
//   'id': WeatherLanguage.indonesian,
//   'it': WeatherLanguage.italian,
//   'ja': WeatherLanguage.japanese,
//   'kr': WeatherLanguage.korean,
//   'la': WeatherLanguage.latvian,
//   'lt': WeatherLanguage.lithuanian,
//   'mk': WeatherLanguage.macedonian,
//   'no': WeatherLanguage.norwegian,
//   'nl': WeatherLanguage.dutch,
//   'pl': WeatherLanguage.polish,
//   'pt': WeatherLanguage.portuguese,
//   'pt_br': WeatherLanguage.portugueseBrazilian,
//   'ro': WeatherLanguage.romanian,
//   'ru': WeatherLanguage.russian,
//   'sv': WeatherLanguage.swedish,
//   'sk': WeatherLanguage.slovak,
//   'sl': WeatherLanguage.slovenian,
//   'sp': WeatherLanguage.spanish,
//   'sr': WeatherLanguage.serbian,
//   'th': WeatherLanguage.thai,
//   'tr': WeatherLanguage.turkish,
//   'ua': WeatherLanguage.ukrainian,
//   'vi': WeatherLanguage.vietnamese,
//   'zh_cn': WeatherLanguage.chineseSimplified,
//   'zh_tw': WeatherLanguage.chineseTraditional,
//   'zu': WeatherLanguage.zulu,
// };
