// ignore_for_file: constant_identifier_names
enum WeatherLanguage {
  afrikaans('af'),
  albanian('al'),
  arabic('ar'),
  azerbaijani('az'),
  bulgarian('bg'),
  catalan('ca'),
  czech('cz'),
  danish('da'),
  german('de'),
  greek('el'),
  english('en'),
  basque('eu'),
  persian('fa'),
  farsi('fa'),
  finnish('fi'),
  french('fr'),
  galician('gl'),
  hebrew('he'),
  hindi('hi'),
  croatian('hr'),
  hungarian('hu'),
  indonesian('id'),
  italian('it'),
  japanese('ja'),
  korean('kr'),
  latvian('la'),
  lithuanian('lt'),
  macedonian('mk'),
  norwegian('no'),
  dutch('nl'),
  polish('pl'),
  portuguese('pt'),
  portugueseBrazilian('pt_br'),
  romanian('ro'),
  russian('ru'),
  swedish('sv'),
  slovak('sk'),
  slovenian('sl'),
  spanish('sp'),
  serbian('sr'),
  thai('th'),
  turkish('tr'),
  ukrainian('ua'),
  vietnamese('vi'),
  chineseSimplified('zh_cn'),
  chineseTraditional('zh_tw'),
  zulu('zu');

  const WeatherLanguage(this.code);

  final String code;
}

// todo - create const map?
// final Map<String, WeatherLanguage> languageCodeReverse = {
//   for (WeatherLanguage wl in WeatherLanguage.values) wl.code: wl
// };

final Map<String, WeatherLanguage> languageCodeReverse =
    <String, WeatherLanguage>{
  WeatherLanguage.afrikaans.code: WeatherLanguage.afrikaans,
  WeatherLanguage.albanian.code: WeatherLanguage.albanian,
  WeatherLanguage.arabic.code: WeatherLanguage.arabic,
  WeatherLanguage.azerbaijani.code: WeatherLanguage.azerbaijani,
  WeatherLanguage.bulgarian.code: WeatherLanguage.bulgarian,
  WeatherLanguage.catalan.code: WeatherLanguage.catalan,
  WeatherLanguage.czech.code: WeatherLanguage.czech,
  WeatherLanguage.danish.code: WeatherLanguage.danish,
  WeatherLanguage.german.code: WeatherLanguage.german,
  WeatherLanguage.greek.code: WeatherLanguage.greek,
  WeatherLanguage.english.code: WeatherLanguage.english,
  WeatherLanguage.basque.code: WeatherLanguage.basque,
  WeatherLanguage.farsi.code: WeatherLanguage.farsi, // persian too
  WeatherLanguage.finnish.code: WeatherLanguage.finnish,
  WeatherLanguage.french.code: WeatherLanguage.french,
  WeatherLanguage.galician.code: WeatherLanguage.galician,
  WeatherLanguage.hebrew.code: WeatherLanguage.hebrew,
  WeatherLanguage.hindi.code: WeatherLanguage.hindi,
  WeatherLanguage.croatian.code: WeatherLanguage.croatian,
  WeatherLanguage.hungarian.code: WeatherLanguage.hungarian,
  WeatherLanguage.indonesian.code: WeatherLanguage.indonesian,
  WeatherLanguage.italian.code: WeatherLanguage.italian,
  WeatherLanguage.japanese.code: WeatherLanguage.japanese,
  WeatherLanguage.korean.code: WeatherLanguage.korean,
  WeatherLanguage.latvian.code: WeatherLanguage.latvian,
  WeatherLanguage.lithuanian.code: WeatherLanguage.lithuanian,
  WeatherLanguage.macedonian.code: WeatherLanguage.macedonian,
  WeatherLanguage.norwegian.code: WeatherLanguage.norwegian,
  WeatherLanguage.dutch.code: WeatherLanguage.dutch,
  WeatherLanguage.polish.code: WeatherLanguage.polish,
  WeatherLanguage.portuguese.code: WeatherLanguage.portuguese,
  WeatherLanguage.portugueseBrazilian.code: WeatherLanguage.portugueseBrazilian,
  WeatherLanguage.romanian.code: WeatherLanguage.romanian,
  WeatherLanguage.russian.code: WeatherLanguage.russian,
  WeatherLanguage.swedish.code: WeatherLanguage.swedish,
  WeatherLanguage.slovak.code: WeatherLanguage.slovak,
  WeatherLanguage.slovenian.code: WeatherLanguage.slovenian,
  WeatherLanguage.spanish.code: WeatherLanguage.spanish,
  WeatherLanguage.serbian.code: WeatherLanguage.serbian,
  WeatherLanguage.thai.code: WeatherLanguage.thai,
  WeatherLanguage.turkish.code: WeatherLanguage.turkish,
  WeatherLanguage.ukrainian.code: WeatherLanguage.ukrainian,
  WeatherLanguage.vietnamese.code: WeatherLanguage.vietnamese,
  WeatherLanguage.chineseSimplified.code: WeatherLanguage.chineseSimplified,
  WeatherLanguage.chineseTraditional.code: WeatherLanguage.chineseTraditional,
  WeatherLanguage.zulu.code: WeatherLanguage.zulu,
};
