name: weather_pack
description: The project is designed to obtain weather via the OpenWeatherMap API. With handy features. :)
version: 0.0.1
#homepage: // todo: ref at github
#repository:  // todo: ref at github
#issue_tracker: // todo: ref at github

environment:
  sdk: ">=2.17.0 <3.0.0" # the lower bound is related to the mixin for Enum

dependencies:
  http: ^0.13.5

dev_dependencies:
  test: ^1.21.6

  lint: ^1.10.0

flutter:
   assets:
    - assets/weather_icons/
