name: weather_pack
description: The project is designed to obtain weather via the OpenWeatherMap API. With handy features. :)
version: 0.0.2
homepage: https://t.me/+AkGV73kZi_Q1YTMy
repository: https://github.com/PackRuble/weather_pack
issue_tracker: https://github.com/PackRuble/weather_pack/issues

environment:
  sdk: ">=2.17.0 <3.0.0" # the lower bound is related to the mixin for Enum

dependencies:
  http: ^0.13.5

dev_dependencies:
  test: ^1.22.1

  lint: ^2.0.1

flutter:
   assets:
    - assets/weather_icons/

screenshots:
  - description: 'LOGO'
    path: assets/images/banner.png
  - description: '(RU) This console mini-application shows how to use the package without flutter.'
    path: example/weather_in_console/assets/result_in_console.gif
