name: weather_pack
description: >-
  The project is designed to obtain weather via the OpenWeatherMap API. 
  With geocoding and units measure. :)
homepage: https://t.me/+AkGV73kZi_Q1YTMy
repository: https://github.com/PackRuble/weather_pack
issue_tracker: https://github.com/PackRuble/weather_pack/issues

version: 1.1.0

environment:
  sdk: ^3.4.0

dependencies:
  http: ^1.3.0

dev_dependencies:
  test: ^1.25.14
  lint: ^2.3.0

flutter:
   assets:
    - assets/weather_icons/

screenshots:
  - description: '<weather_pack> package banner'
    path: assets/images/banner.png
  - description: '(RU) This console mini-application shows how to use the package without flutter.'
    path: example/weather_in_console/assets/result_in_console.gif

funding:
  - https://t.me/+AkGV73kZi_Q1YTMy

topics:
  - weather
  - openweathermap
  - geocoding
  - weather-forecast
  - units-measure
