name: weather_in_console
description: A sample command-line application for getting weather data using weather_pack.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  interact: ^2.2.0
  weather_pack:
    path: ../../

dev_dependencies:
  lint: ^2.0.1