name: weather_in_console
description: A sample command-line application for getting weather data using weather_pack.
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  interact: ^2.1.1
  weather_pack: ^0.0.2

dev_dependencies:
  lint: ^2.0.1