name: 'Publish package'

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: '1.2.3'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: 'Publish Dart/Flutter package'
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutterBranch: stable
          flutter: false
          skipTests: true
          dryRunOnly: false
