name: 'Publish package'

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: 'Publish Dart package'
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
          flutterBranch: stable
          flutter: false
          skipTests: true
          dryRunOnly: false
          force: false
